language: node_js
node_js:
    - "10"
install:
    - npm i -g @vue/cli
    - npm i
script:
    - npm run build-demo
cache:
    directories:
        - "node_modules"
notifications:
    email: false
deploy:
  - provider: pages
    skip-cleanup: true
    local_dir: demo
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    repo: <blackfaded>/<vue-typewrite>
    keep-history: true
    target-branch: master
    on:
        branch: master
  - provider: npm
    email: "rene.heinen@gmx.net"
    api_key: $NPM_TOKEN