language: node_js
node_js:
    - "10"
install:
    - npm i -g @vue/cli
    - npm i
script:
    - npm run build-demo
    - npm run build-plugin
cache:
    directories:
        - "node_modules"
notifications:
    email: false
branches:
  only:
  - master
deploy:
  - provider: pages
    skip-cleanup: true
    local_dir: demo
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    repo: blackfaded/vue-typewrite
    keep-history: true
    target-branch: gh-pages
  - provider: npm
    email: "rene.heinen@gmx.net"
    api_key: $NPM_TOKEN
    skip_cleanup: true